name: dart_multiaddr
description: Composable and future-proof network addresses.
version: 0.1.0
repository: https://github.com/YogiLiu/dart_multiaddr

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
